name: Open Liberty Image Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        run: |
          curl -sLO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          cosign version

  pull-and-validate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #- name: Log in to Open Liberty Registry
       # run: echo "${{ secrets.IBM_CLOUD_API_KEY }}" | docker login icr.io -u iamapikey --password-stdin

      - name: Pull Open Liberty Images (excluding beta versions)
        run: |
          for image in $(curl -s https://icr.io/v2/appcafe/open-liberty/tags/list | jq -r '.tags[]' | grep '^24.0.0.3$'); do
            docker pull icr.io/appcafe/open-liberty:$image
          done

      - name: Validate Image Signature
        run: |
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "icr.io/appcafe/open-liberty"); do
            cosign verify --key config/public-key.pem $image
          done

  upload-to-artifactory:
    runs-on: ubuntu-latest
    needs: pull-and-validate
    steps:
      - name: Log in to JFrog Artifactory
        run: docker login ${{ secrets.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USER }} -p ${{ secrets.ARTIFACTORY_PASS }}

      - name: Push Images to JFrog Artifactory
        run: |
          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "icr.io/appcafe/open-liberty"); do
            docker tag $image ${{ secrets.ARTIFACTORY_REPO }}/$image
            docker push ${{ secrets.ARTIFACTORY_REPO }}/$image
          done
